# Generated by Django 5.2.2 on 2025-06-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20250605_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledpost',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='scheduler.scheduledpost')),
            ],
        ),
    ]
