# Generated by Django 5.2.2 on 2025-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_scheduledpost_options_postanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpost',
            name='account',
        ),
        migrations.RemoveField(
            model_name='scheduledpost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
